#!/bin/bash

clear

### Install binutils

    if hash apt 2>/dev/null                        #Debian
    then
        binutils=$(sudo apt install binutils)
        clear
        python3 DTB.py
    elif hash pacman 2>/dev/null                    #ArchLinux
    then
        binutils=$(sudo pacman -S binutils)
        clear
        python3 DTB.py
    elif hash eopkg 2>/dev/null			    #Solus
    then
    	binutils=$(sudo eopkg it binutils)
	clear
	python3 DTB.py
    else
        binutils="Your distribution was not detected"
    	echo $binutils
        echo "You Inatlled binutils? (Y/n)"
	read binutils_install
        if [ $binutils_install == "y" ]
        then
	    clear
	    python3 DTB.py
	elif [ $binutils_install == "Y" ]
        then
	    clear
	    python3 DTB.py
	else
	    echo "please install binutils.."
	fi
    fi
